theme: jekyll-theme-slate
title: Welcome to Oscar E Lopez's ePortfolio
description:  This online portfolio is a showcase of my learning experience at Southern New Hampshire University. At the very least the online portfolio should clearly illustrate the progress from good to great, you should see the personal growth of having learned the key concepts tought at SNHU. 
